CREATE TABLE rubros(id text(1), rubro text(10));
CREATE TABLE diario(
id int primary key unique,
id_cta int,
fecha text(20),
importe real,
ref int,
FOREIGN KEY(id_cta) REFERENCES cuentas(id),
FOREIGN KEY(ref) REFERENCES cuentas(id)
);
CREATE TABLE sub_rubros(
id integer primary key not null,
rubro text(1),
sub_rubro text(64),
FOREIGN KEY(rubro) REFERENCES rubros(id)
);
CREATE TABLE cuentas (
id int primary key not null,
sub_rubro int,
cuenta text(256),
FOREIGN KEY (sub_rubro) REFERENCES sub_rubros(id)
);
CREATE VIEW plan AS
SELECT rubros.rubro, sub_rubros.sub_rubro, cuentas.cuenta
from rubros
join sub_rubros on sub_rubros.rubro=rubros.id 
join cuentas on cuentas.sub_rubro=sub_rubros.id 
ORDER BY rubros.id;
CREATE VIEW saldo_cuentas as select (select cuenta from cuentas where id=id_cta) as Cuenta, sum(importe) as importe from diario GROUP BY Cuenta;
CREATE VIEW mayor_pesos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 1) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 1 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 1) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 1 ORDER BY a.fecha;
CREATE VIEW mayor_dolares AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 2) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 2 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 2) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 2 ORDER BY a.fecha;
CREATE VIEW mayor_otros AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 3) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 3 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 3) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 3 ORDER BY a.fecha;
CREATE VIEW mayor_ciudad AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 4) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 4 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 4) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 4 ORDER BY a.fecha;
CREATE VIEW mayor_santander AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 5) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 5 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 5) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 5 ORDER BY a.fecha;
CREATE VIEW mayor_icbc AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 6) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 6 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 6) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 6 ORDER BY a.fecha;
CREATE VIEW mayor_classic AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 7) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 7 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 7) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 7 ORDER BY a.fecha;
CREATE VIEW mayor_piso AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 8) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 8 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 8) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 8 ORDER BY a.fecha;
CREATE VIEW mayor_cochera AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 9) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 9 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 9) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 9 ORDER BY a.fecha;
CREATE VIEW mayor_personal AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 10) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 10 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 10) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 10 ORDER BY a.fecha;
CREATE VIEW mayor_hipoteca AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 11) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 11 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 11) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 11 ORDER BY a.fecha;
CREATE VIEW mayor_visa_rio AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 12) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 12 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 12) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 12 ORDER BY a.fecha;
CREATE VIEW mayor_amex_rio AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 13) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 13 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 13) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 13 ORDER BY a.fecha;
CREATE VIEW mayor_visa_icbc AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 14) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 14 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 14) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 14 ORDER BY a.fecha;
CREATE VIEW mayor_master_icbc AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 15) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 15 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 15) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 15 ORDER BY a.fecha;
CREATE VIEW mayor_carnes AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 16) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 16 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 16) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 16 ORDER BY a.fecha;
CREATE VIEW mayor_feria AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 17) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 17 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 17) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 17 ORDER BY a.fecha;
CREATE VIEW mayor_supermercados AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 18) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 18 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 18) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 18 ORDER BY a.fecha;
CREATE VIEW mayor_indumentaria AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 19) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 19 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 19) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 19 ORDER BY a.fecha;
CREATE VIEW mayor_salud AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 20) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 20 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 20) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 20 ORDER BY a.fecha;
CREATE VIEW mayor_diarios_y_revistas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 21) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 21 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 21) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 21 ORDER BY a.fecha;
CREATE VIEW mayor_bibliografia AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 22) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 22 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 22) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 22 ORDER BY a.fecha;
CREATE VIEW mayor_pastas_frescas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 23) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 23 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 23) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 23 ORDER BY a.fecha;
CREATE VIEW mayor_huevos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 24) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 24 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 24) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 24 ORDER BY a.fecha;
CREATE VIEW mayor_comestibles AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 25) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 25 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 25) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 25 ORDER BY a.fecha;
CREATE VIEW mayor_lacteos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 26) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 26 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 26) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 26 ORDER BY a.fecha;
CREATE VIEW mayor_fiambres AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 27) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 27 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 27) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 27 ORDER BY a.fecha;
CREATE VIEW mayor_panificados AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 28) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 28 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 28) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 28 ORDER BY a.fecha;
CREATE VIEW mayor_galletitas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 29) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 29 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 29) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 29 ORDER BY a.fecha;
CREATE VIEW mayor_limpieza AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 30) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 30 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 30) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 30 ORDER BY a.fecha;
CREATE VIEW mayor_bazar AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 31) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 31 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 31) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 31 ORDER BY a.fecha;
CREATE VIEW mayor_electrodomesticos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 32) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 32 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 32) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 32 ORDER BY a.fecha;
CREATE VIEW mayor_iva AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 33) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 33 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 33) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 33 ORDER BY a.fecha;
CREATE VIEW mayor_patentes AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 34) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 34 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 34) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 34 ORDER BY a.fecha;
CREATE VIEW mayor_abl AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 35) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 35 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 35) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 35 ORDER BY a.fecha;
CREATE VIEW mayor_intereses AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 36) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 36 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 36) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 36 ORDER BY a.fecha;
CREATE VIEW mayor_internet AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 37) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 37 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 37) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 37 ORDER BY a.fecha;
CREATE VIEW mayor_telefonia AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 38) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 38 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 38) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 38 ORDER BY a.fecha;
CREATE VIEW mayor_edesur AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 39) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 39 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 39) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 39 ORDER BY a.fecha;
CREATE VIEW mayor_aysa AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 40) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 40 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 40) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 40 ORDER BY a.fecha;
CREATE VIEW mayor_metrogas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 41) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 41 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 41) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 41 ORDER BY a.fecha;
CREATE VIEW mayor_club AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 42) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 42 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 42) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 42 ORDER BY a.fecha;
CREATE VIEW mayor_expensas_piso AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 43) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 43 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 43) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 43 ORDER BY a.fecha;
CREATE VIEW mayor_expensas_cochera AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 44) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 44 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 44) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 44 ORDER BY a.fecha;
CREATE VIEW mayor_reparaciones_hogareñas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 45) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 45 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 45) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 45 ORDER BY a.fecha;
CREATE VIEW mayor_service_coche AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 46) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 46 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 46) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 46 ORDER BY a.fecha;
CREATE VIEW mayor_reparaciones_coche AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 47) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 47 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 47) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 47 ORDER BY a.fecha;
CREATE VIEW mayor_estacionamiento AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 48) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 48 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 48) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 48 ORDER BY a.fecha;
CREATE VIEW mayor_combustibles AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 49) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 49 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 49) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 49 ORDER BY a.fecha;
CREATE VIEW mayor_refrigerios AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 50) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 50 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 50) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 50 ORDER BY a.fecha;
CREATE VIEW mayor_peajes AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 51) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 51 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 51) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 51 ORDER BY a.fecha;
CREATE VIEW mayor_sube AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 52) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 52 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 52) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 52 ORDER BY a.fecha;
CREATE VIEW mayor_pasajes AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 53) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 53 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 53) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 53 ORDER BY a.fecha;
CREATE VIEW mayor_taxis_y_remises AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 54) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 54 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 54) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 54 ORDER BY a.fecha;
CREATE VIEW mayor_ibm_argentina AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 55) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 55 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 55) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 55 ORDER BY a.fecha;
CREATE VIEW mayor_impuestos_varios AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 56) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 56 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 56) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 56 ORDER BY a.fecha;
CREATE VIEW mayor_credito_personal_rio AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 57) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 57 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 57) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 57 ORDER BY a.fecha;
CREATE VIEW mayor_seguros_rio AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 58) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 58 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 58) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 58 ORDER BY a.fecha;
CREATE VIEW mayor_ahorro_compras_con_tarjeta AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 59) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 59 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 59) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 59 ORDER BY a.fecha;
CREATE VIEW mayor_devolucion_de_iva AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 60) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 60 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 60) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 60 ORDER BY a.fecha;
CREATE VIEW mayor_ajustes_capital AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 61) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 61 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 61) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 61 ORDER BY a.fecha;
CREATE VIEW mayor_intereses_ganados AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 62) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 62 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 62) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 62 ORDER BY a.fecha;
CREATE VIEW mayor_gastos_bancarios AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 63) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 63 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 63) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 63 ORDER BY a.fecha;
CREATE VIEW mayor_visa_banco_ciudad AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 64) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 64 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 64) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 64 ORDER BY a.fecha;
CREATE VIEW mayor_bonificaiones_y_promociones AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 65) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 65 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 65) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 65 ORDER BY a.fecha;
CREATE VIEW mayor_utiles_y_papeleria AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 66) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 66 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 66) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 66 ORDER BY a.fecha;
CREATE VIEW mayor_farmacia AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 67) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 67 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 67) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 67 ORDER BY a.fecha;
CREATE VIEW mayor_rosa_y_carlos_prestamos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 68) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 68 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 68) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 68 ORDER BY a.fecha;
CREATE VIEW mayor_levadura AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 69) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 69 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 69) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 69 ORDER BY a.fecha;
CREATE VIEW mayor_manteca AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 70) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 70 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 70) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 70 ORDER BY a.fecha;
CREATE VIEW mayor_queso_por_salut AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 71) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 71 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 71) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 71 ORDER BY a.fecha;
CREATE VIEW mayor_queso_semi_duro AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 72) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 72 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 72) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 72 ORDER BY a.fecha;
CREATE VIEW mayor_quesos_duros AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 73) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 73 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 73) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 73 ORDER BY a.fecha;
CREATE VIEW mayor_untable AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 74) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 74 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 74) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 74 ORDER BY a.fecha;
CREATE VIEW mayor_yogurt AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 75) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 75 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 75) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 75 ORDER BY a.fecha;
CREATE VIEW mayor_leche_lv AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 76) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 76 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 76) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 76 ORDER BY a.fecha;
CREATE VIEW mayor_aceitunas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 77) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 77 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 77) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 77 ORDER BY a.fecha;
CREATE VIEW mayor_dulces_y_mermeladas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 78) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 78 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 78) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 78 ORDER BY a.fecha;
CREATE VIEW mayor_tapas_de_empanadas_y_tartas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 79) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 79 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 79) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 79 ORDER BY a.fecha;
CREATE VIEW mayor_merenguitos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 80) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 80 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 80) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 80 ORDER BY a.fecha;
CREATE VIEW mayor_yerba AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 81) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 81 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 81) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 81 ORDER BY a.fecha;
CREATE VIEW mayor_fideos_secos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 82) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 82 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 82) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 82 ORDER BY a.fecha;
CREATE VIEW mayor_papel_higiénico AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 83) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 83 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 83) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 83 ORDER BY a.fecha;
CREATE VIEW mayor_papel_p_cocina AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 84) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 84 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 84) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 84 ORDER BY a.fecha;
CREATE VIEW mayor_milanesa_de_soja AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 85) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 85 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 85) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 85 ORDER BY a.fecha;
CREATE VIEW mayor_congelados AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 86) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 86 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 86) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 86 ORDER BY a.fecha;
CREATE VIEW mayor_arroz AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 87) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 87 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 87) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 87 ORDER BY a.fecha;
CREATE VIEW mayor_harinas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 88) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 88 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 88) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 88 ORDER BY a.fecha;
CREATE VIEW mayor_insecticidas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 89) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 89 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 89) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 89 ORDER BY a.fecha;
CREATE VIEW mayor_lavandina AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 90) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 90 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 90) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 90 ORDER BY a.fecha;
CREATE VIEW mayor_pan_rallado AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 91) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 91 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 91) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 91 ORDER BY a.fecha;
CREATE VIEW mayor_atun_enlatado AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 92) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 92 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 92) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 92 ORDER BY a.fecha;
CREATE VIEW mayor_sopas_instantaneas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 93) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 93 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 93) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 93 ORDER BY a.fecha;
CREATE VIEW mayor_bizcochuelos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 94) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 94 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 94) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 94 ORDER BY a.fecha;
CREATE VIEW mayor_flanes_y_postres AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 95) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 95 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 95) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 95 ORDER BY a.fecha;
CREATE VIEW mayor_vinagres AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 96) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 96 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 96) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 96 ORDER BY a.fecha;
CREATE VIEW mayor_cepillos_dentales AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 97) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 97 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 97) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 97 ORDER BY a.fecha;
CREATE VIEW mayor_polvo_p_hornear AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 98) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 98 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 98) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 98 ORDER BY a.fecha;
CREATE VIEW mayor_agua_mineral AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 99) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 99 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 99) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 99 ORDER BY a.fecha;
CREATE VIEW mayor_azucar_impalpable AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 100) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 100 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 100) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 100 ORDER BY a.fecha;
CREATE VIEW mayor_cosmeticos_varios AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 101) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 101 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 101) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 101 ORDER BY a.fecha;
CREATE VIEW mayor_lechuga AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 102) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 102 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 102) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 102 ORDER BY a.fecha;
CREATE VIEW mayor_tomate AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 103) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 103 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 103) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 103 ORDER BY a.fecha;
CREATE VIEW mayor_zanahoria AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 104) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 104 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 104) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 104 ORDER BY a.fecha;
CREATE VIEW mayor_cebolla_blanca AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 105) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 105 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 105) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 105 ORDER BY a.fecha;
CREATE VIEW mayor_cebolla_verde AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 106) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 106 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 106) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 106 ORDER BY a.fecha;
CREATE VIEW mayor_puerro AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 107) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 107 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 107) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 107 ORDER BY a.fecha;
CREATE VIEW mayor_calabaza AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 108) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 108 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 108) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 108 ORDER BY a.fecha;
CREATE VIEW mayor_papa AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 109) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 109 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 109) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 109 ORDER BY a.fecha;
CREATE VIEW mayor_batata AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 110) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 110 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 110) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 110 ORDER BY a.fecha;
CREATE VIEW mayor_manzana AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 111) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 111 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 111) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 111 ORDER BY a.fecha;
CREATE VIEW mayor_banana AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 112) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 112 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 112) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 112 ORDER BY a.fecha;
CREATE VIEW mayor_naranja AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 113) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 113 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 113) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 113 ORDER BY a.fecha;
CREATE VIEW mayor_mandarina AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 114) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 114 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 114) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 114 ORDER BY a.fecha;
CREATE VIEW mayor_pera AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 115) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 115 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 115) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 115 ORDER BY a.fecha;
CREATE VIEW mayor_limon AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 116) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 116 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 116) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 116 ORDER BY a.fecha;
CREATE VIEW mayor_pomelo AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 117) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 117 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 117) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 117 ORDER BY a.fecha;
CREATE VIEW mayor_ciruela AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 118) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 118 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 118) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 118 ORDER BY a.fecha;
CREATE VIEW mayor_durazno AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 119) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 119 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 119) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 119 ORDER BY a.fecha;
CREATE VIEW mayor_mango AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 120) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 120 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 120) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 120 ORDER BY a.fecha;
CREATE VIEW mayor_melon AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 121) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 121 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 121) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 121 ORDER BY a.fecha;
CREATE VIEW mayor_sandía AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 122) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 122 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 122) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 122 ORDER BY a.fecha;
CREATE VIEW mayor_nueces AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 123) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 123 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 123) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 123 ORDER BY a.fecha;
CREATE VIEW mayor_almendras AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 124) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 124 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 124) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 124 ORDER BY a.fecha;
CREATE VIEW mayor_maní AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 125) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 125 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 125) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 125 ORDER BY a.fecha;
CREATE VIEW mayor_castañas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 126) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 126 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 126) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 126 ORDER BY a.fecha;
CREATE VIEW mayor_ciruelas_secas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 127) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 127 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 127) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 127 ORDER BY a.fecha;
CREATE VIEW mayor_pasas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 128) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 128 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 128) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 128 ORDER BY a.fecha;
CREATE VIEW mayor_endivia AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 129) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 129 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 129) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 129 ORDER BY a.fecha;
CREATE VIEW mayor_cereales AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 130) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 130 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 130) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 130 ORDER BY a.fecha;
CREATE VIEW mayor_azucar_blanco AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 131) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 131 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 131) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 131 ORDER BY a.fecha;
CREATE VIEW mayor_detergente AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 132) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 132 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 132) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 132 ORDER BY a.fecha;
CREATE VIEW mayor_kiwi AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 133) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 133 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 133) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 133 ORDER BY a.fecha;
CREATE VIEW mayor_libros AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 134) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 134 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 134) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 134 ORDER BY a.fecha;
CREATE VIEW mayor_propinas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 135) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 135 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 135) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 135 ORDER BY a.fecha;
CREATE VIEW mayor_golosinas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 136) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 136 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 136) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 136 ORDER BY a.fecha;
CREATE VIEW mayor_dulce_de_membrillo_en_barra AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 137) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 137 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 137) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 137 ORDER BY a.fecha;
CREATE VIEW mayor_leche_la_serenisima_x_250cc AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 138) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 138 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 138) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 138 ORDER BY a.fecha;
CREATE VIEW mayor_dentifricos AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 139) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 139 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 139) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 139 ORDER BY a.fecha;
CREATE VIEW mayor_cotillon AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 140) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 140 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 140) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 140 ORDER BY a.fecha;
CREATE VIEW mayor_bolsas_plasticas AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 141) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 141 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 141) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 141 ORDER BY a.fecha;
CREATE VIEW mayor_desodorante_de_ambientes AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 142) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 142 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 142) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 142 ORDER BY a.fecha;
CREATE VIEW mayor_peluqueria AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 143) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 143 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 143) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 143 ORDER BY a.fecha;
CREATE VIEW mayor_cine AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 144) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 144 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 144) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 144 ORDER BY a.fecha;
CREATE VIEW plan_detalle AS
SELECT cuentas.id, rubros.rubro, sub_rubros.sub_rubro, cuentas.cuenta
from rubros
join sub_rubros on sub_rubros.rubro=rubros.id 
join cuentas on cuentas.sub_rubro=sub_rubros.id 
ORDER BY rubros.id;
CREATE VIEW plan_balance as
SELECT cuentas.id as id_cuenta, rubros.id as id_rubro, sub_rubros.id as id_subrubro, rubros.rubro as rubro, sub_rubros.sub_rubro as subrubro, cuentas.cuenta as cuenta
FROM rubros
join sub_rubros on sub_rubros.rubro=rubros.id 
join cuentas on cuentas.sub_rubro=sub_rubros.id 
ORDER BY rubros.id;
CREATE VIEW debitos AS
SELECT
cuentas.id as id_cta, cuentas.cuenta as cuenta, 
case when sum(diario.importe) is null then 0 else sum(diario.importe) end as importe
FROM cuentas left join diario on diario.id_cta=cuentas.id
GROUP BY cuentas.id ORDER BY cuentas.id;
CREATE VIEW creditos AS
SELECT
cuentas.id as id_cta, cuentas.cuenta as cuenta, 
case when sum(diario.importe) is null then 0 else sum(diario.importe) end as importe
FROM cuentas left join diario on diario.ref=cuentas.id
GROUP BY cuentas.id ORDER BY cuentas.id;
CREATE VIEW sumas AS
SELECT cuentas.id as id_cuenta, rubros.id as id_rubro, sub_rubros.id as id_subrubro, rubros.rubro as rubro,
 sub_rubros.sub_rubro as subrubro, cuentas.cuenta as cuenta, debitos.importe as debe, creditos.importe as haber
FROM rubros
join sub_rubros on sub_rubros.rubro=rubros.id 
join cuentas on cuentas.sub_rubro=sub_rubros.id 
join debitos on cuentas.id=debitos.id_cta
join creditos on cuentas.id=creditos.id_cta
ORDER BY rubros.id;
CREATE VIEW sumas_y_saldos AS
SELECT cuentas.id as id_cuenta, rubros.id as id_rubro, sub_rubros.id as id_subrubro, rubros.rubro as rubro,
 sub_rubros.sub_rubro as subrubro, cuentas.cuenta as cuenta, debitos.importe as debe, creditos.importe as haber,
 case when debitos.importe > creditos.importe then debitos.importe - creditos.importe else 0 end as saldo_debe,
 case when debitos.importe > creditos.importe then 0 else creditos.importe - debitos.importe end as saldo_debe
FROM rubros
join sub_rubros on sub_rubros.rubro=rubros.id 
join cuentas on cuentas.sub_rubro=sub_rubros.id 
join debitos on cuentas.id=debitos.id_cta
join creditos on cuentas.id=creditos.id_cta
ORDER BY rubros.id;
CREATE VIEW mayor_rio AS SELECT ( SELECT cuenta FROM cuentas WHERE id = 5) as mayor_cuenta , a.fecha, a.id, b.cuenta, a.importe as debe, 0 as haber from diario a join cuentas b ON a.ref = b.id  WHERE id_cta = 5 UNION SELECT (SELECT cuenta FROM cuentas WHERE id = 5) as mayor_cuenta , a.fecha, a.id, b.cuenta, 0 as debe, a.importe as haber from diario a join cuentas b ON a.id_cta = b.id  WHERE ref = 5 ORDER BY a.fecha;
