# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_rubro', models.IntegerField(blank=True, null=True)),
                ('cuenta', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cta', models.IntegerField()),
                ('fecha', models.CharField(max_length=20)),
                ('importe', models.FloatField()),
                ('ref', models.IntegerField()),
            ],
            options={
                'db_table': 'diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('rubro', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rubros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubRubros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rubro', models.CharField(max_length=1)),
                ('sub_rubro', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sub_rubros',
                'managed': False,
            },
        ),
    ]
